# Generated by Django 4.2.6 on 2023-10-28 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_operations_dashboard", "can view operations dashboard"),
                    ("perform_transfers", "can perform transfers"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
