# Generated by Django 4.2.6 on 2023-10-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_useradditional_created_at_useradditional_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useradditional",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
