# Generated by Django 4.2.6 on 2023-10-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_tag_task_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.CreateModel(
            name="TaskTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo.tag"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="tags_new",
            field=models.ManyToManyField(
                related_name="tasks", through="todo.TaskTag", to="todo.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasktag",
            constraint=models.UniqueConstraint(
                fields=("task_id", "tag_id"), name="unique_task_tag"
            ),
        ),
    ]
