class StatusChoice:
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"

    CHOICE_LIST = [
        (PENDING, PENDING),
        (IN_PROGRESS, IN_PROGRESS),
        (COMPLETED, COMPLETED),
        (ARCHIVED, ARCHIVED)
    ]