# Generated by Django 4.2.6 on 2023-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0005_alter_account_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
